### ISSUE TITLE
先讲CNN，再说RNN是不是比较好一些？

### ISSUE THREAD

**Issue by Gumilton** [BU-GU/Cuckoo#1]
CNN研究比较透彻，有很多性质在CNN上说比较容易，然后再到RNN的时候，提一下，因为对于一个模型，毕竟CNN的深度是确定的，而RNN的深度在时间上是可变的，所以理解起来CNN容易一些。

**Comment by Jonah-Bu** [comment]
我觉得挺好，CNN更直观，我把CNN和RNN顺序调整一下
